### ISSUE TITLE
Client HTTP lib for Zig, or server HTTP lib for Zig, or both?

### ISSUE THREAD

**Issue by paul-hammant** [ducdetronquito/h11#17]
Perhaps the README should clarify

**Comment by ducdetronquito** [comment]
Hi @paul-hammant,

Like it's python counterpart ([python-hyper/h11](https://github.com/python-hyper/h11)), *h11* aims to provide **both HTTP client and server** logic.

As of yet, only the client workflow has been developed as describe currently in the README, which is:

1. Create an `h11.Client` object to track the state of a single HTTP/1.1 connection.
2. Serialize a Request event with `var bytes = client.send(...)` and write those bytes to the network.
3. Read bytes off the network and pass them to `client.receive_data(...)`
4. Retrieve one or more HTTP "events" by calling `client.nextEvent()` until it returns an `EndOfMessage` event or an error.

The server part is not yet started, but I expect to be able to show some meaningful results by the end of May, with something like a basic HTTP server (following the [basic http client](https://github.com/ducdetronquito/h11/tree/master/examples/basic_client) example).

I will mention this information in the README when it's done :)
