### ISSUE TITLE
Response status code must not be more than 3 digits

### ISSUE THREAD

**Issue by ducdetronquito** [ducdetronquito/h11#29]
Cf: https://tools.ietf.org/html/rfc7230#section-3.1.2

Currently the following malformed response is accepted, but it should not:

```zig
test "Status code with more than 3 digits should fail" {
    var headers: [0]Header = undefined;
    const content = "HTTP/1.1 123456789 Some reason phrase\r\n\r\n\r\n";

    const response = try Response.parse(content, &headers);

    expectError(error.Invalid, response);
}
````

**Comment by newsamaritan** [comment]
`        if (statusLine[13] != ' ') {
            return error.Invalid;
        }`

**Comment by ducdetronquito** [comment]
Hi @newsamaritan,

Sorry for the late response, I didn't receive any notification for your message !

I fixed the bug with a slightly modified version of your snippet, thank you for the help :)

Have a nice day 🌴
