### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by 89z** [ducdetronquito/h11#54]
I see no docs are available:

https://github.com/ducdetronquito/h11#usage

but couldnt you at least post a single example? I am looking for a very basic HTTPS client.

**Comment by 89z** [comment]
Hm, I think this is what I am looking for:

https://github.com/ducdetronquito/requestz

**Comment by ducdetronquito** [comment]
Hi @89z,

Exactly, `h11` is just the implementation of the HTTP/1.1 protocol but it does not do any actual network calls.
On the other hand [requestz](https://github.com/ducdetronquito/requestz) is an actuall HTTP client, but I should warn you that it is very much in progress.

It is not yet available for Zig 0.9.0, so in the meantime I would recommend to use [zfetch](https://github.com/truemedian/zfetch).

Have a nice day !

**Comment by 89z** [comment]
FYI zFetch is now archived:

https://github.com/truemedian/zfetch
